### ISSUE TITLE
Is there a serious mistake ?

### ISSUE THREAD

**Issue by supnobita** [TerraTech/lizardfs-flexvolume#2]
I review your code and i saw:
https://github.com/TerraTech/lizardfs-flexvolume/blob/70483e8c207061a8fdff2d7d0233987200c33b5b/lizardfs#L106

I don't know what is a meaning of those line ?
  mfsmount -H "${HOST}" -S / "${TMPDIR}"
	mkdir -p "${TMPDIR}/$LFSFOLDER"
  umount "${TMPDIR}"
  rm -rf "${TMPDIR}"
Why do you mount and after that you umont ?
why do you unmount, then you didn't check the result of umount command ? and you delete mount point ? if umount is unsuccessful, you will delete all file on your storage ?

**Comment by supnobita** [comment]
After review your commit, I try to comment these lines and test with K8s. And It works.
Thank for your script.

**Comment by TerraTech** [comment]
Good catch, I missed that during review of #1 and that certainly needs to have better error handling.  I will try to find some time next week and fortify it.

**Comment by TerraTech** [comment]
@supnobita I have reverted the commit, and will revisit the logic in domount().  It was one of those things where I needed to fork the original project to make some updates, but didn't do much refactoring for what already was working.
