### ISSUE TITLE
Not finding plugin

### ISSUE THREAD

**Issue by htbase** [TerraTech/lizardfs-flexvolume#4]
Hi there

When I try to follow the description, I'm able to create and "see" the volumes but when I try to deploy a pod using the volume, I get the following:

Sep 18 01:19:11 gcpkube1 kubelet[22656]: E0918 01:19:11.449680   22656 desired_state_of_world_populator.go:311] Failed to add volume "lizardfs" (specName: "mfs-volume") for pod "c642fcf1-bae0-11e8-b19e-0a6bcb3944c8" to desiredStateOfWorld. err=failed to get Plugin from volumeSpec for volume "mfs-volume" err=no volume plugin matched

We created the folders and followed the description

Any idea why?

Thanks

**Comment by TerraTech** [comment]
Are you using the 'manual' method, or the ready-2-run image?

If manual method, what version is the kubelet?

I'd also like to see your pod spec.

Overall, FlexVolume is being phased out for CSI so I'm not sure how much time I'd be able to put into furthering lizardfs-flexvolume ability.  When I upgrade our cluster to >=1.10.0 I plan to revisit this and see what it will take to mount LizardFS through CSI.

In short, we have switched over to CoreOS tectonic (hyperkube-v1.9.6) for the kubernetes infrastructure, and I just haven't had time to wire LizardFS into it.  Most of what we used LizardFS for was replaced with iSCSI mounts (which was a temporary bandaid until CSI is fully supported).  With that said, 
lizardfs-flexvolume used to work pretty well, until we switched to a terraformed tectonic core.

IMHO, FlexVolume was a hacky and fragile solution to providing 3rd party storage drivers, and CSI should become the defacto implementation which is where I'll focus my efforts once tectonic bumps up to >=1.10.0.

Also, please read though:  https://github.com/kubernetes/community/blob/master/contributors/devel/flexvolume.md

In particular the ```--enable-controller-attach-detach``` option, as that has caused me a fair amount of grief in the past.

**Comment by htbase** [comment]
Thanks for the response

Here is the version info:

Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T18:02:47Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

I'm running the deployment examples file you provided to the volumes and all

I'm using Ubuntu 16.04 for the OS

**Comment by htbase** [comment]
Now the problem is gone with the --enable-controller-attach-detach but when I try to run deployment script, it returns:

Sep 18 16:21:21 gcpkube1 kubelet[22656]: E0918 16:21:21.027009   22656 nestedpendingoperations.go:267] Operation for "\"flexvolume-fq/lizardfs/d81462e0-bb5e-11e8-b19e-0a6bcb3944c8-mfs-volume-1\" (\"d81462e0-bb5e-11e8-b19e-0a6bcb3944c8\")" failed. No retries permitted until 2018-09-18 16:21:25.026975055 +0000 UTC m=+56040.052194467 (durationBeforeRetry 4s). Error: "MountVolume.SetUp failed for volume \"mfs-volume-1\" (UniqueName: \"flexvolume-fq/lizardfs/d81462e0-bb5e-11e8-b19e-0a6bcb3944c8-mfs-volume-1\") pod \"testfs-6d5c87fcb8-d6mph\" (UID: \"d81462e0-bb5e-11e8-b19e-0a6bcb3944c8\") : mount command failed, status: Failure, reason: Failed to mount lizardfs at: /var/lib/kubelet/pods/d81462e0-bb5e-11e8-b19e-0a6bcb3944c8/volumes/fq~lizardfs/mfs-volume-1 :: [mfsmaster register error: No such file or directory]"

**Comment by htbase** [comment]
Sorry, just wanted to see if you could help with a hint on the above
